import { createClient } from '@supabase/supabase-js';

// Lazy initialized Supabase client helper
export function getSupabaseClient() {
  const defaultUrl = 'https://ketmrgmuhgelxdpqzxrq.supabase.co';
  const defaultKey = 'sb_publishable_Zph252PPdN06eVnIiiNGaA_QdPFt9li';

  let url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || defaultUrl;
  let anonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || defaultKey;

  // Filter out outdated/invalid key references and old JWTs
  if (anonKey.includes('qd3fs') || anonKey.includes('oanqetk') || anonKey.startsWith('eyJ') || !anonKey || anonKey.includes('your-anon-key')) {
    anonKey = defaultKey;
  }
  if (url.includes('oanqetk') || !url || url.includes('your-project-id')) {
    url = defaultUrl;
  }

  console.log('[Supabase Client Setup]', { url, anonKeyPreview: anonKey.substring(0, 15) });

  if (!url || !anonKey || url.trim() === '' || anonKey.trim() === '' || url.includes('your-project-id') || anonKey.includes('your-anon-key')) {
    return null;
  }

  try {
    return createClient(url, anonKey, {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
      global: {
        fetch: (reqUrl, options = {}) => {
          const headers = new Headers(options?.headers || {});
          headers.set('apikey', anonKey);
          headers.set('Authorization', `Bearer ${anonKey}`);
          return fetch(reqUrl, { ...options, headers });
        },
      },
    });
  } catch {
    return null;
  }
}

export const SUPABASE_FEEDBACK_TABLE_SQL = `-- Run this SQL query in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create citizen_feedback table including photo column for picture / landmark evidence
CREATE TABLE IF NOT EXISTS public.citizen_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'general',
  name TEXT NOT NULL,
  contact TEXT NOT NULL,
  barangay TEXT NOT NULL,
  description TEXT NOT NULL,
  photo TEXT, -- Stores photo / landmark evidence (Image Data URL or Supabase Storage URL)
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. If your table was created earlier, run this line to add the photo column:
ALTER TABLE public.citizen_feedback ADD COLUMN IF NOT EXISTS photo TEXT;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.citizen_feedback ENABLE ROW LEVEL SECURITY;

-- 4. Allow public anonymous & authenticated inserts for feedback reports
DROP POLICY IF EXISTS "Allow public insert to citizen_feedback" ON public.citizen_feedback;
CREATE POLICY "Allow public insert to citizen_feedback"
ON public.citizen_feedback
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 5. Allow public selection of feedback reports
DROP POLICY IF EXISTS "Allow public select from citizen_feedback" ON public.citizen_feedback;
CREATE POLICY "Allow public select from citizen_feedback"
ON public.citizen_feedback
FOR SELECT
TO anon, authenticated
USING (true);
`;

// Function to verify Supabase connection status & table availability
export async function checkSupabaseConnection(): Promise<{
  configured: boolean;
  connected: boolean;
  tableExists: boolean;
  message: string;
  sqlToRun?: string;
  url?: string;
}> {
  const defaultUrl = 'https://ketmrgmuhgelxdpqzxrq.supabase.co';
  const defaultKey = 'sb_publishable_Zph252PPdN06eVnIiiNGaA_QdPFt9li';

  let url = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || defaultUrl;
  let anonKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || defaultKey;

  if (anonKey.includes('qd3fs') || anonKey.includes('oanqetk') || (anonKey.startsWith('eyJ') && !anonKey.includes('ketmrg')) || !anonKey || anonKey.includes('your-anon-key')) {
    anonKey = defaultKey;
  }
  if (url.includes('oanqetk') || !url || url.includes('your-project-id')) {
    url = defaultUrl;
  }

  if (!url || !anonKey || url.trim() === '' || anonKey.trim() === '' || url.includes('your-project-id') || anonKey.includes('your-anon-key')) {
    return {
      configured: false,
      connected: false,
      tableExists: false,
      message: 'Supabase environment variables are missing or set to placeholder values.',
      sqlToRun: SUPABASE_FEEDBACK_TABLE_SQL,
    };
  }

  try {
    const supabase = createClient(url, anonKey, {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
      global: {
        fetch: (reqUrl, options = {}) => {
          const headers = new Headers(options?.headers || {});
          headers.set('apikey', anonKey);
          headers.set('Authorization', `Bearer ${anonKey}`);
          return fetch(reqUrl, { ...options, headers });
        },
      },
    });
    // Ping table
    const { error } = await supabase.from('citizen_feedback').select('id').limit(1);

    if (error) {
      if (error.code === '42P01' || error.message.includes('does not exist') || error.message.includes('relation')) {
        return {
          configured: true,
          connected: true,
          tableExists: false,
          message: 'Connected to Supabase, but table "citizen_feedback" has not been created yet in your Supabase database.',
          sqlToRun: SUPABASE_FEEDBACK_TABLE_SQL,
          url,
        };
      }

      if (error.message.includes('fetch failed') || error.message.includes('TypeError') || error.message.includes('Failed to fetch')) {
        return {
          configured: true,
          connected: false,
          tableExists: false,
          message: `Network error connecting to Supabase URL (${url}). Please verify that your Supabase project URL is active and reachable.`,
          sqlToRun: SUPABASE_FEEDBACK_TABLE_SQL,
          url,
        };
      }

      return {
        configured: true,
        connected: false,
        tableExists: false,
        message: `Connected to Supabase with response note: ${error.message}`,
        sqlToRun: SUPABASE_FEEDBACK_TABLE_SQL,
        url,
      };
    }

    return {
      configured: true,
      connected: true,
      tableExists: true,
      message: 'Supabase is fully connected and table "citizen_feedback" is ready!',
      url,
    };
  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : 'Unknown connection error';
    return {
      configured: true,
      connected: false,
      tableExists: false,
      message: `Failed to connect to Supabase: ${errorMessage}`,
      sqlToRun: SUPABASE_FEEDBACK_TABLE_SQL,
      url,
    };
  }
}
